/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutDevicesRouteImport } from './routes/_layout/_devices'
import { Route as LayoutDevicesDevicesIndexRouteImport } from './routes/_layout/_devices/devices/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDevicesRoute = LayoutDevicesRouteImport.update({
  id: '/_devices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevicesDevicesIndexRoute =
  LayoutDevicesDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => LayoutDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof LayoutDevicesDevicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof LayoutDevicesDevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_devices': typeof LayoutDevicesRouteWithChildren
  '/_layout/_devices/devices/': typeof LayoutDevicesDevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/devices'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devices'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/_devices'
    | '/_layout/_devices/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_devices': {
      id: '/_layout/_devices'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutDevicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_devices/devices/': {
      id: '/_layout/_devices/devices/'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LayoutDevicesDevicesIndexRouteImport
      parentRoute: typeof LayoutDevicesRoute
    }
  }
}

interface LayoutDevicesRouteChildren {
  LayoutDevicesDevicesIndexRoute: typeof LayoutDevicesDevicesIndexRoute
}

const LayoutDevicesRouteChildren: LayoutDevicesRouteChildren = {
  LayoutDevicesDevicesIndexRoute: LayoutDevicesDevicesIndexRoute,
}

const LayoutDevicesRouteWithChildren = LayoutDevicesRoute._addFileChildren(
  LayoutDevicesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutDevicesRoute: typeof LayoutDevicesRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDevicesRoute: LayoutDevicesRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
