/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutDevicesRouteImport } from './routes/_layout/_devices'
import { Route as LayoutDevicesDevicesIndexRouteImport } from './routes/_layout/_devices/devices/index'
import { Route as LayoutDevicesDevicesDevice_idMotorsRouteImport } from './routes/_layout/_devices/devices/$device_id/_motors'
import { Route as LayoutDevicesDevicesDevice_idMotorsMotorsIndexRouteImport } from './routes/_layout/_devices/devices/$device_id/_motors/motors/index'
import { Route as LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRouteImport } from './routes/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/index'

const LayoutDevicesDevicesDevice_idRouteImport = createFileRoute(
  '/_layout/_devices/devices/$device_id',
)()

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDevicesRoute = LayoutDevicesRouteImport.update({
  id: '/_devices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevicesDevicesDevice_idRoute =
  LayoutDevicesDevicesDevice_idRouteImport.update({
    id: '/devices/$device_id',
    path: '/devices/$device_id',
    getParentRoute: () => LayoutDevicesRoute,
  } as any)
const LayoutDevicesDevicesIndexRoute =
  LayoutDevicesDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => LayoutDevicesRoute,
  } as any)
const LayoutDevicesDevicesDevice_idMotorsRoute =
  LayoutDevicesDevicesDevice_idMotorsRouteImport.update({
    id: '/_motors',
    getParentRoute: () => LayoutDevicesDevicesDevice_idRoute,
  } as any)
const LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute =
  LayoutDevicesDevicesDevice_idMotorsMotorsIndexRouteImport.update({
    id: '/motors/',
    path: '/motors/',
    getParentRoute: () => LayoutDevicesDevicesDevice_idMotorsRoute,
  } as any)
const LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute =
  LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRouteImport.update({
    id: '/motors/$motor_id/',
    path: '/motors/$motor_id/',
    getParentRoute: () => LayoutDevicesDevicesDevice_idMotorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof LayoutDevicesDevicesIndexRoute
  '/devices/$device_id': typeof LayoutDevicesDevicesDevice_idMotorsRouteWithChildren
  '/devices/$device_id/motors': typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute
  '/devices/$device_id/motors/$motor_id': typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof LayoutDevicesDevicesIndexRoute
  '/devices/$device_id': typeof LayoutDevicesDevicesDevice_idMotorsRouteWithChildren
  '/devices/$device_id/motors': typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute
  '/devices/$device_id/motors/$motor_id': typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_devices': typeof LayoutDevicesRouteWithChildren
  '/_layout/_devices/devices/': typeof LayoutDevicesDevicesIndexRoute
  '/_layout/_devices/devices/$device_id': typeof LayoutDevicesDevicesDevice_idRouteWithChildren
  '/_layout/_devices/devices/$device_id/_motors': typeof LayoutDevicesDevicesDevice_idMotorsRouteWithChildren
  '/_layout/_devices/devices/$device_id/_motors/motors/': typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute
  '/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/': typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/devices/$device_id'
    | '/devices/$device_id/motors'
    | '/devices/$device_id/motors/$motor_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/devices/$device_id'
    | '/devices/$device_id/motors'
    | '/devices/$device_id/motors/$motor_id'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/_devices'
    | '/_layout/_devices/devices/'
    | '/_layout/_devices/devices/$device_id'
    | '/_layout/_devices/devices/$device_id/_motors'
    | '/_layout/_devices/devices/$device_id/_motors/motors/'
    | '/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_devices': {
      id: '/_layout/_devices'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutDevicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_devices/devices/$device_id': {
      id: '/_layout/_devices/devices/$device_id'
      path: '/devices/$device_id'
      fullPath: '/devices/$device_id'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idRouteImport
      parentRoute: typeof LayoutDevicesRoute
    }
    '/_layout/_devices/devices/': {
      id: '/_layout/_devices/devices/'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LayoutDevicesDevicesIndexRouteImport
      parentRoute: typeof LayoutDevicesRoute
    }
    '/_layout/_devices/devices/$device_id/_motors': {
      id: '/_layout/_devices/devices/$device_id/_motors'
      path: '/devices/$device_id'
      fullPath: '/devices/$device_id'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idMotorsRouteImport
      parentRoute: typeof LayoutDevicesDevicesDevice_idRoute
    }
    '/_layout/_devices/devices/$device_id/_motors/motors/': {
      id: '/_layout/_devices/devices/$device_id/_motors/motors/'
      path: '/motors'
      fullPath: '/devices/$device_id/motors'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRouteImport
      parentRoute: typeof LayoutDevicesDevicesDevice_idMotorsRoute
    }
    '/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/': {
      id: '/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/'
      path: '/motors/$motor_id'
      fullPath: '/devices/$device_id/motors/$motor_id'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRouteImport
      parentRoute: typeof LayoutDevicesDevicesDevice_idMotorsRoute
    }
  }
}

interface LayoutDevicesDevicesDevice_idMotorsRouteChildren {
  LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute: typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute
  LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute: typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute
}

const LayoutDevicesDevicesDevice_idMotorsRouteChildren: LayoutDevicesDevicesDevice_idMotorsRouteChildren =
  {
    LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute:
      LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute,
    LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute:
      LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute,
  }

const LayoutDevicesDevicesDevice_idMotorsRouteWithChildren =
  LayoutDevicesDevicesDevice_idMotorsRoute._addFileChildren(
    LayoutDevicesDevicesDevice_idMotorsRouteChildren,
  )

interface LayoutDevicesDevicesDevice_idRouteChildren {
  LayoutDevicesDevicesDevice_idMotorsRoute: typeof LayoutDevicesDevicesDevice_idMotorsRouteWithChildren
}

const LayoutDevicesDevicesDevice_idRouteChildren: LayoutDevicesDevicesDevice_idRouteChildren =
  {
    LayoutDevicesDevicesDevice_idMotorsRoute:
      LayoutDevicesDevicesDevice_idMotorsRouteWithChildren,
  }

const LayoutDevicesDevicesDevice_idRouteWithChildren =
  LayoutDevicesDevicesDevice_idRoute._addFileChildren(
    LayoutDevicesDevicesDevice_idRouteChildren,
  )

interface LayoutDevicesRouteChildren {
  LayoutDevicesDevicesIndexRoute: typeof LayoutDevicesDevicesIndexRoute
  LayoutDevicesDevicesDevice_idRoute: typeof LayoutDevicesDevicesDevice_idRouteWithChildren
}

const LayoutDevicesRouteChildren: LayoutDevicesRouteChildren = {
  LayoutDevicesDevicesIndexRoute: LayoutDevicesDevicesIndexRoute,
  LayoutDevicesDevicesDevice_idRoute:
    LayoutDevicesDevicesDevice_idRouteWithChildren,
}

const LayoutDevicesRouteWithChildren = LayoutDevicesRoute._addFileChildren(
  LayoutDevicesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutDevicesRoute: typeof LayoutDevicesRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDevicesRoute: LayoutDevicesRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
