/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as FetchErrorRouteImport } from './routes/fetch-error'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUserdashboardRouteImport } from './routes/_layout/userdashboard'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutViewprofileRouteImport } from './routes/_layout/_viewprofile'
import { Route as LayoutUsersRouteImport } from './routes/_layout/_users'
import { Route as LayoutPondsRouteImport } from './routes/_layout/_ponds'
import { Route as LayoutLocationsRouteImport } from './routes/_layout/_locations'
import { Route as LayoutDevicesRouteImport } from './routes/_layout/_devices'
import { Route as LayoutApfcRouteImport } from './routes/_layout/_apfc'
import { Route as LayoutDefaultSettingsIndexRouteImport } from './routes/_layout/default-settings/index'
import { Route as LayoutUsersAddIndexRouteImport } from './routes/_layout/users/add/index'
import { Route as LayoutViewprofileViewprofileIndexRouteImport } from './routes/_layout/_viewprofile/viewprofile/index'
import { Route as LayoutUsersUsersIndexRouteImport } from './routes/_layout/_users/users/index'
import { Route as LayoutPondsPondsIndexRouteImport } from './routes/_layout/_ponds/ponds/index'
import { Route as LayoutLocationsLocationsIndexRouteImport } from './routes/_layout/_locations/locations/index'
import { Route as LayoutDevicesDevicesIndexRouteImport } from './routes/_layout/_devices/devices/index'
import { Route as LayoutApfcApfcIndexRouteImport } from './routes/_layout/_apfc/apfc/index'
import { Route as LayoutUsersUser_idUpdateIndexRouteImport } from './routes/_layout/users/$user_id/update/index'
import { Route as LayoutApfcApfc_idUpdateSettingsIndexRouteImport } from './routes/_layout/apfc/$apfc_id/update-settings/index'
import { Route as LayoutPondsPondsPond_idIndexRouteImport } from './routes/_layout/_ponds/ponds/$pond_id/index'
import { Route as LayoutUsersUsersUser_idPondsRouteImport } from './routes/_layout/_users/users/$user_id/_ponds'
import { Route as LayoutUsersUsersUser_idDevicesRouteImport } from './routes/_layout/_users/users/$user_id/_devices'
import { Route as LayoutUsersUsersUser_idApfcRouteImport } from './routes/_layout/_users/users/$user_id/_apfc'
import { Route as LayoutDevicesDevicesDevice_idStarterboxRouteImport } from './routes/_layout/_devices/devices/$device_id/starterbox'
import { Route as LayoutDevicesDevicesDevice_idMotorsRouteImport } from './routes/_layout/_devices/devices/$device_id/_motors'
import { Route as LayoutUsersUsersUser_idGatewaysIndexRouteImport } from './routes/_layout/_users/users/$user_id/gateways/index'
import { Route as LayoutLocationsLocationsLocation_idGatewaysIndexRouteImport } from './routes/_layout/_locations/locations/$location_id/gateways/index'
import { Route as LayoutApfcApfcApfc_idSettingsIndexRouteImport } from './routes/_layout/_apfc/apfc/$apfc_id/settings/index'
import { Route as LayoutApfcApfcApfc_idDetailsIndexRouteImport } from './routes/_layout/_apfc/apfc/$apfc_id/details/index'
import { Route as LayoutApfcApfcApfc_idActivityIndexRouteImport } from './routes/_layout/_apfc/apfc/$apfc_id/activity/index'
import { Route as LayoutUsersUsersUser_idPondsPondsIndexRouteImport } from './routes/_layout/_users/users/$user_id/_ponds/ponds/index'
import { Route as LayoutUsersUsersUser_idDevicesDevicesIndexRouteImport } from './routes/_layout/_users/users/$user_id/_devices/devices/index'
import { Route as LayoutUsersUsersUser_idApfcApfcIndexRouteImport } from './routes/_layout/_users/users/$user_id/_apfc/apfc/index'
import { Route as LayoutDevicesDevicesDevice_idMotorsMotorsIndexRouteImport } from './routes/_layout/_devices/devices/$device_id/_motors/motors/index'
import { Route as LayoutUsersUsersUser_idPondsPondsPond_idIndexRouteImport } from './routes/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/index'
import { Route as LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRouteImport } from './routes/_layout/_users/users/$user_id/_devices/devices/$device_id/index'
import { Route as LayoutUsersUsersUser_idApfcApfcApfc_idIndexRouteImport } from './routes/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/index'
import { Route as LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRouteImport } from './routes/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/index'
import { Route as LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRouteImport } from './routes/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/index'
import { Route as LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRouteImport } from './routes/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/settings/index'
import { Route as LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRouteImport } from './routes/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/details/index'
import { Route as LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRouteImport } from './routes/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/activity/index'
import { Route as LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRouteImport } from './routes/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/$motor_id/index'

const LayoutUsersUsersUser_idRouteImport = createFileRoute(
  '/_layout/_users/users/$user_id',
)()
const LayoutDevicesDevicesDevice_idRouteImport = createFileRoute(
  '/_layout/_devices/devices/$device_id',
)()

const FetchErrorRoute = FetchErrorRouteImport.update({
  id: '/fetch-error',
  path: '/fetch-error',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUserdashboardRoute = LayoutUserdashboardRouteImport.update({
  id: '/userdashboard',
  path: '/userdashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewprofileRoute = LayoutViewprofileRouteImport.update({
  id: '/_viewprofile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/_users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPondsRoute = LayoutPondsRouteImport.update({
  id: '/_ponds',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLocationsRoute = LayoutLocationsRouteImport.update({
  id: '/_locations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevicesRoute = LayoutDevicesRouteImport.update({
  id: '/_devices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApfcRoute = LayoutApfcRouteImport.update({
  id: '/_apfc',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDefaultSettingsIndexRoute =
  LayoutDefaultSettingsIndexRouteImport.update({
    id: '/default-settings/',
    path: '/default-settings/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutUsersUsersUser_idRoute = LayoutUsersUsersUser_idRouteImport.update({
  id: '/users/$user_id',
  path: '/users/$user_id',
  getParentRoute: () => LayoutUsersRoute,
} as any)
const LayoutDevicesDevicesDevice_idRoute =
  LayoutDevicesDevicesDevice_idRouteImport.update({
    id: '/devices/$device_id',
    path: '/devices/$device_id',
    getParentRoute: () => LayoutDevicesRoute,
  } as any)
const LayoutUsersAddIndexRoute = LayoutUsersAddIndexRouteImport.update({
  id: '/users/add/',
  path: '/users/add/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewprofileViewprofileIndexRoute =
  LayoutViewprofileViewprofileIndexRouteImport.update({
    id: '/viewprofile/',
    path: '/viewprofile/',
    getParentRoute: () => LayoutViewprofileRoute,
  } as any)
const LayoutUsersUsersIndexRoute = LayoutUsersUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LayoutUsersRoute,
} as any)
const LayoutPondsPondsIndexRoute = LayoutPondsPondsIndexRouteImport.update({
  id: '/ponds/',
  path: '/ponds/',
  getParentRoute: () => LayoutPondsRoute,
} as any)
const LayoutLocationsLocationsIndexRoute =
  LayoutLocationsLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => LayoutLocationsRoute,
  } as any)
const LayoutDevicesDevicesIndexRoute =
  LayoutDevicesDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => LayoutDevicesRoute,
  } as any)
const LayoutApfcApfcIndexRoute = LayoutApfcApfcIndexRouteImport.update({
  id: '/apfc/',
  path: '/apfc/',
  getParentRoute: () => LayoutApfcRoute,
} as any)
const LayoutUsersUser_idUpdateIndexRoute =
  LayoutUsersUser_idUpdateIndexRouteImport.update({
    id: '/users/$user_id/update/',
    path: '/users/$user_id/update/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApfcApfc_idUpdateSettingsIndexRoute =
  LayoutApfcApfc_idUpdateSettingsIndexRouteImport.update({
    id: '/apfc/$apfc_id/update-settings/',
    path: '/apfc/$apfc_id/update-settings/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPondsPondsPond_idIndexRoute =
  LayoutPondsPondsPond_idIndexRouteImport.update({
    id: '/ponds/$pond_id/',
    path: '/ponds/$pond_id/',
    getParentRoute: () => LayoutPondsRoute,
  } as any)
const LayoutUsersUsersUser_idPondsRoute =
  LayoutUsersUsersUser_idPondsRouteImport.update({
    id: '/_ponds',
    getParentRoute: () => LayoutUsersUsersUser_idRoute,
  } as any)
const LayoutUsersUsersUser_idDevicesRoute =
  LayoutUsersUsersUser_idDevicesRouteImport.update({
    id: '/_devices',
    getParentRoute: () => LayoutUsersUsersUser_idRoute,
  } as any)
const LayoutUsersUsersUser_idApfcRoute =
  LayoutUsersUsersUser_idApfcRouteImport.update({
    id: '/_apfc',
    getParentRoute: () => LayoutUsersUsersUser_idRoute,
  } as any)
const LayoutDevicesDevicesDevice_idStarterboxRoute =
  LayoutDevicesDevicesDevice_idStarterboxRouteImport.update({
    id: '/starterbox',
    path: '/starterbox',
    getParentRoute: () => LayoutDevicesDevicesDevice_idRoute,
  } as any)
const LayoutDevicesDevicesDevice_idMotorsRoute =
  LayoutDevicesDevicesDevice_idMotorsRouteImport.update({
    id: '/_motors',
    getParentRoute: () => LayoutDevicesDevicesDevice_idRoute,
  } as any)
const LayoutUsersUsersUser_idGatewaysIndexRoute =
  LayoutUsersUsersUser_idGatewaysIndexRouteImport.update({
    id: '/gateways/',
    path: '/gateways/',
    getParentRoute: () => LayoutUsersUsersUser_idRoute,
  } as any)
const LayoutLocationsLocationsLocation_idGatewaysIndexRoute =
  LayoutLocationsLocationsLocation_idGatewaysIndexRouteImport.update({
    id: '/locations/$location_id/gateways/',
    path: '/locations/$location_id/gateways/',
    getParentRoute: () => LayoutLocationsRoute,
  } as any)
const LayoutApfcApfcApfc_idSettingsIndexRoute =
  LayoutApfcApfcApfc_idSettingsIndexRouteImport.update({
    id: '/apfc/$apfc_id/settings/',
    path: '/apfc/$apfc_id/settings/',
    getParentRoute: () => LayoutApfcRoute,
  } as any)
const LayoutApfcApfcApfc_idDetailsIndexRoute =
  LayoutApfcApfcApfc_idDetailsIndexRouteImport.update({
    id: '/apfc/$apfc_id/details/',
    path: '/apfc/$apfc_id/details/',
    getParentRoute: () => LayoutApfcRoute,
  } as any)
const LayoutApfcApfcApfc_idActivityIndexRoute =
  LayoutApfcApfcApfc_idActivityIndexRouteImport.update({
    id: '/apfc/$apfc_id/activity/',
    path: '/apfc/$apfc_id/activity/',
    getParentRoute: () => LayoutApfcRoute,
  } as any)
const LayoutUsersUsersUser_idPondsPondsIndexRoute =
  LayoutUsersUsersUser_idPondsPondsIndexRouteImport.update({
    id: '/ponds/',
    path: '/ponds/',
    getParentRoute: () => LayoutUsersUsersUser_idPondsRoute,
  } as any)
const LayoutUsersUsersUser_idDevicesDevicesIndexRoute =
  LayoutUsersUsersUser_idDevicesDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => LayoutUsersUsersUser_idDevicesRoute,
  } as any)
const LayoutUsersUsersUser_idApfcApfcIndexRoute =
  LayoutUsersUsersUser_idApfcApfcIndexRouteImport.update({
    id: '/apfc/',
    path: '/apfc/',
    getParentRoute: () => LayoutUsersUsersUser_idApfcRoute,
  } as any)
const LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute =
  LayoutDevicesDevicesDevice_idMotorsMotorsIndexRouteImport.update({
    id: '/motors/',
    path: '/motors/',
    getParentRoute: () => LayoutDevicesDevicesDevice_idMotorsRoute,
  } as any)
const LayoutUsersUsersUser_idPondsPondsPond_idIndexRoute =
  LayoutUsersUsersUser_idPondsPondsPond_idIndexRouteImport.update({
    id: '/ponds/$pond_id/',
    path: '/ponds/$pond_id/',
    getParentRoute: () => LayoutUsersUsersUser_idPondsRoute,
  } as any)
const LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRoute =
  LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRouteImport.update({
    id: '/devices/$device_id/',
    path: '/devices/$device_id/',
    getParentRoute: () => LayoutUsersUsersUser_idDevicesRoute,
  } as any)
const LayoutUsersUsersUser_idApfcApfcApfc_idIndexRoute =
  LayoutUsersUsersUser_idApfcApfcApfc_idIndexRouteImport.update({
    id: '/apfc/$apfc_id/',
    path: '/apfc/$apfc_id/',
    getParentRoute: () => LayoutUsersUsersUser_idApfcRoute,
  } as any)
const LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute =
  LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRouteImport.update({
    id: '/motors/$motor_id/',
    path: '/motors/$motor_id/',
    getParentRoute: () => LayoutDevicesDevicesDevice_idMotorsRoute,
  } as any)
const LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRoute =
  LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRouteImport.update({
    id: '/ponds/$pond_id/motors/',
    path: '/ponds/$pond_id/motors/',
    getParentRoute: () => LayoutUsersUsersUser_idPondsRoute,
  } as any)
const LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRoute =
  LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRouteImport.update({
    id: '/apfc/$apfc_id/settings/',
    path: '/apfc/$apfc_id/settings/',
    getParentRoute: () => LayoutUsersUsersUser_idApfcRoute,
  } as any)
const LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRoute =
  LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRouteImport.update({
    id: '/apfc/$apfc_id/details/',
    path: '/apfc/$apfc_id/details/',
    getParentRoute: () => LayoutUsersUsersUser_idApfcRoute,
  } as any)
const LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRoute =
  LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRouteImport.update({
    id: '/apfc/$apfc_id/activity/',
    path: '/apfc/$apfc_id/activity/',
    getParentRoute: () => LayoutUsersUsersUser_idApfcRoute,
  } as any)
const LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRoute =
  LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRouteImport.update(
    {
      id: '/ponds/$pond_id/motors/$motor_id/',
      path: '/ponds/$pond_id/motors/$motor_id/',
      getParentRoute: () => LayoutUsersUsersUser_idPondsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fetch-error': typeof FetchErrorRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/userdashboard': typeof LayoutUserdashboardRoute
  '/default-settings': typeof LayoutDefaultSettingsIndexRoute
  '/apfc': typeof LayoutApfcApfcIndexRoute
  '/devices': typeof LayoutDevicesDevicesIndexRoute
  '/locations': typeof LayoutLocationsLocationsIndexRoute
  '/ponds': typeof LayoutPondsPondsIndexRoute
  '/users': typeof LayoutUsersUsersIndexRoute
  '/viewprofile': typeof LayoutViewprofileViewprofileIndexRoute
  '/users/add': typeof LayoutUsersAddIndexRoute
  '/devices/$device_id': typeof LayoutDevicesDevicesDevice_idMotorsRouteWithChildren
  '/devices/$device_id/starterbox': typeof LayoutDevicesDevicesDevice_idStarterboxRoute
  '/users/$user_id': typeof LayoutUsersUsersUser_idPondsRouteWithChildren
  '/ponds/$pond_id': typeof LayoutPondsPondsPond_idIndexRoute
  '/apfc/$apfc_id/update-settings': typeof LayoutApfcApfc_idUpdateSettingsIndexRoute
  '/users/$user_id/update': typeof LayoutUsersUser_idUpdateIndexRoute
  '/apfc/$apfc_id/activity': typeof LayoutApfcApfcApfc_idActivityIndexRoute
  '/apfc/$apfc_id/details': typeof LayoutApfcApfcApfc_idDetailsIndexRoute
  '/apfc/$apfc_id/settings': typeof LayoutApfcApfcApfc_idSettingsIndexRoute
  '/locations/$location_id/gateways': typeof LayoutLocationsLocationsLocation_idGatewaysIndexRoute
  '/users/$user_id/gateways': typeof LayoutUsersUsersUser_idGatewaysIndexRoute
  '/devices/$device_id/motors': typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute
  '/users/$user_id/apfc': typeof LayoutUsersUsersUser_idApfcApfcIndexRoute
  '/users/$user_id/devices': typeof LayoutUsersUsersUser_idDevicesDevicesIndexRoute
  '/users/$user_id/ponds': typeof LayoutUsersUsersUser_idPondsPondsIndexRoute
  '/devices/$device_id/motors/$motor_id': typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute
  '/users/$user_id/apfc/$apfc_id': typeof LayoutUsersUsersUser_idApfcApfcApfc_idIndexRoute
  '/users/$user_id/devices/$device_id': typeof LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRoute
  '/users/$user_id/ponds/$pond_id': typeof LayoutUsersUsersUser_idPondsPondsPond_idIndexRoute
  '/users/$user_id/apfc/$apfc_id/activity': typeof LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRoute
  '/users/$user_id/apfc/$apfc_id/details': typeof LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRoute
  '/users/$user_id/apfc/$apfc_id/settings': typeof LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRoute
  '/users/$user_id/ponds/$pond_id/motors': typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRoute
  '/users/$user_id/ponds/$pond_id/motors/$motor_id': typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fetch-error': typeof FetchErrorRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/userdashboard': typeof LayoutUserdashboardRoute
  '/default-settings': typeof LayoutDefaultSettingsIndexRoute
  '/apfc': typeof LayoutApfcApfcIndexRoute
  '/devices': typeof LayoutDevicesDevicesIndexRoute
  '/locations': typeof LayoutLocationsLocationsIndexRoute
  '/ponds': typeof LayoutPondsPondsIndexRoute
  '/users': typeof LayoutUsersUsersIndexRoute
  '/viewprofile': typeof LayoutViewprofileViewprofileIndexRoute
  '/users/add': typeof LayoutUsersAddIndexRoute
  '/devices/$device_id': typeof LayoutDevicesDevicesDevice_idMotorsRouteWithChildren
  '/devices/$device_id/starterbox': typeof LayoutDevicesDevicesDevice_idStarterboxRoute
  '/users/$user_id': typeof LayoutUsersUsersUser_idPondsRouteWithChildren
  '/ponds/$pond_id': typeof LayoutPondsPondsPond_idIndexRoute
  '/apfc/$apfc_id/update-settings': typeof LayoutApfcApfc_idUpdateSettingsIndexRoute
  '/users/$user_id/update': typeof LayoutUsersUser_idUpdateIndexRoute
  '/apfc/$apfc_id/activity': typeof LayoutApfcApfcApfc_idActivityIndexRoute
  '/apfc/$apfc_id/details': typeof LayoutApfcApfcApfc_idDetailsIndexRoute
  '/apfc/$apfc_id/settings': typeof LayoutApfcApfcApfc_idSettingsIndexRoute
  '/locations/$location_id/gateways': typeof LayoutLocationsLocationsLocation_idGatewaysIndexRoute
  '/users/$user_id/gateways': typeof LayoutUsersUsersUser_idGatewaysIndexRoute
  '/devices/$device_id/motors': typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute
  '/users/$user_id/apfc': typeof LayoutUsersUsersUser_idApfcApfcIndexRoute
  '/users/$user_id/devices': typeof LayoutUsersUsersUser_idDevicesDevicesIndexRoute
  '/users/$user_id/ponds': typeof LayoutUsersUsersUser_idPondsPondsIndexRoute
  '/devices/$device_id/motors/$motor_id': typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute
  '/users/$user_id/apfc/$apfc_id': typeof LayoutUsersUsersUser_idApfcApfcApfc_idIndexRoute
  '/users/$user_id/devices/$device_id': typeof LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRoute
  '/users/$user_id/ponds/$pond_id': typeof LayoutUsersUsersUser_idPondsPondsPond_idIndexRoute
  '/users/$user_id/apfc/$apfc_id/activity': typeof LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRoute
  '/users/$user_id/apfc/$apfc_id/details': typeof LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRoute
  '/users/$user_id/apfc/$apfc_id/settings': typeof LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRoute
  '/users/$user_id/ponds/$pond_id/motors': typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRoute
  '/users/$user_id/ponds/$pond_id/motors/$motor_id': typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/fetch-error': typeof FetchErrorRoute
  '/_layout/_apfc': typeof LayoutApfcRouteWithChildren
  '/_layout/_devices': typeof LayoutDevicesRouteWithChildren
  '/_layout/_locations': typeof LayoutLocationsRouteWithChildren
  '/_layout/_ponds': typeof LayoutPondsRouteWithChildren
  '/_layout/_users': typeof LayoutUsersRouteWithChildren
  '/_layout/_viewprofile': typeof LayoutViewprofileRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/userdashboard': typeof LayoutUserdashboardRoute
  '/_layout/default-settings/': typeof LayoutDefaultSettingsIndexRoute
  '/_layout/_apfc/apfc/': typeof LayoutApfcApfcIndexRoute
  '/_layout/_devices/devices/': typeof LayoutDevicesDevicesIndexRoute
  '/_layout/_locations/locations/': typeof LayoutLocationsLocationsIndexRoute
  '/_layout/_ponds/ponds/': typeof LayoutPondsPondsIndexRoute
  '/_layout/_users/users/': typeof LayoutUsersUsersIndexRoute
  '/_layout/_viewprofile/viewprofile/': typeof LayoutViewprofileViewprofileIndexRoute
  '/_layout/users/add/': typeof LayoutUsersAddIndexRoute
  '/_layout/_devices/devices/$device_id': typeof LayoutDevicesDevicesDevice_idRouteWithChildren
  '/_layout/_devices/devices/$device_id/_motors': typeof LayoutDevicesDevicesDevice_idMotorsRouteWithChildren
  '/_layout/_devices/devices/$device_id/starterbox': typeof LayoutDevicesDevicesDevice_idStarterboxRoute
  '/_layout/_users/users/$user_id': typeof LayoutUsersUsersUser_idRouteWithChildren
  '/_layout/_users/users/$user_id/_apfc': typeof LayoutUsersUsersUser_idApfcRouteWithChildren
  '/_layout/_users/users/$user_id/_devices': typeof LayoutUsersUsersUser_idDevicesRouteWithChildren
  '/_layout/_users/users/$user_id/_ponds': typeof LayoutUsersUsersUser_idPondsRouteWithChildren
  '/_layout/_ponds/ponds/$pond_id/': typeof LayoutPondsPondsPond_idIndexRoute
  '/_layout/apfc/$apfc_id/update-settings/': typeof LayoutApfcApfc_idUpdateSettingsIndexRoute
  '/_layout/users/$user_id/update/': typeof LayoutUsersUser_idUpdateIndexRoute
  '/_layout/_apfc/apfc/$apfc_id/activity/': typeof LayoutApfcApfcApfc_idActivityIndexRoute
  '/_layout/_apfc/apfc/$apfc_id/details/': typeof LayoutApfcApfcApfc_idDetailsIndexRoute
  '/_layout/_apfc/apfc/$apfc_id/settings/': typeof LayoutApfcApfcApfc_idSettingsIndexRoute
  '/_layout/_locations/locations/$location_id/gateways/': typeof LayoutLocationsLocationsLocation_idGatewaysIndexRoute
  '/_layout/_users/users/$user_id/gateways/': typeof LayoutUsersUsersUser_idGatewaysIndexRoute
  '/_layout/_devices/devices/$device_id/_motors/motors/': typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute
  '/_layout/_users/users/$user_id/_apfc/apfc/': typeof LayoutUsersUsersUser_idApfcApfcIndexRoute
  '/_layout/_users/users/$user_id/_devices/devices/': typeof LayoutUsersUsersUser_idDevicesDevicesIndexRoute
  '/_layout/_users/users/$user_id/_ponds/ponds/': typeof LayoutUsersUsersUser_idPondsPondsIndexRoute
  '/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/': typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute
  '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/': typeof LayoutUsersUsersUser_idApfcApfcApfc_idIndexRoute
  '/_layout/_users/users/$user_id/_devices/devices/$device_id/': typeof LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRoute
  '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/': typeof LayoutUsersUsersUser_idPondsPondsPond_idIndexRoute
  '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/activity/': typeof LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRoute
  '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/details/': typeof LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRoute
  '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/settings/': typeof LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRoute
  '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/': typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRoute
  '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/$motor_id/': typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fetch-error'
    | '/dashboard'
    | '/userdashboard'
    | '/default-settings'
    | '/apfc'
    | '/devices'
    | '/locations'
    | '/ponds'
    | '/users'
    | '/viewprofile'
    | '/users/add'
    | '/devices/$device_id'
    | '/devices/$device_id/starterbox'
    | '/users/$user_id'
    | '/ponds/$pond_id'
    | '/apfc/$apfc_id/update-settings'
    | '/users/$user_id/update'
    | '/apfc/$apfc_id/activity'
    | '/apfc/$apfc_id/details'
    | '/apfc/$apfc_id/settings'
    | '/locations/$location_id/gateways'
    | '/users/$user_id/gateways'
    | '/devices/$device_id/motors'
    | '/users/$user_id/apfc'
    | '/users/$user_id/devices'
    | '/users/$user_id/ponds'
    | '/devices/$device_id/motors/$motor_id'
    | '/users/$user_id/apfc/$apfc_id'
    | '/users/$user_id/devices/$device_id'
    | '/users/$user_id/ponds/$pond_id'
    | '/users/$user_id/apfc/$apfc_id/activity'
    | '/users/$user_id/apfc/$apfc_id/details'
    | '/users/$user_id/apfc/$apfc_id/settings'
    | '/users/$user_id/ponds/$pond_id/motors'
    | '/users/$user_id/ponds/$pond_id/motors/$motor_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fetch-error'
    | '/dashboard'
    | '/userdashboard'
    | '/default-settings'
    | '/apfc'
    | '/devices'
    | '/locations'
    | '/ponds'
    | '/users'
    | '/viewprofile'
    | '/users/add'
    | '/devices/$device_id'
    | '/devices/$device_id/starterbox'
    | '/users/$user_id'
    | '/ponds/$pond_id'
    | '/apfc/$apfc_id/update-settings'
    | '/users/$user_id/update'
    | '/apfc/$apfc_id/activity'
    | '/apfc/$apfc_id/details'
    | '/apfc/$apfc_id/settings'
    | '/locations/$location_id/gateways'
    | '/users/$user_id/gateways'
    | '/devices/$device_id/motors'
    | '/users/$user_id/apfc'
    | '/users/$user_id/devices'
    | '/users/$user_id/ponds'
    | '/devices/$device_id/motors/$motor_id'
    | '/users/$user_id/apfc/$apfc_id'
    | '/users/$user_id/devices/$device_id'
    | '/users/$user_id/ponds/$pond_id'
    | '/users/$user_id/apfc/$apfc_id/activity'
    | '/users/$user_id/apfc/$apfc_id/details'
    | '/users/$user_id/apfc/$apfc_id/settings'
    | '/users/$user_id/ponds/$pond_id/motors'
    | '/users/$user_id/ponds/$pond_id/motors/$motor_id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_layout'
    | '/fetch-error'
    | '/_layout/_apfc'
    | '/_layout/_devices'
    | '/_layout/_locations'
    | '/_layout/_ponds'
    | '/_layout/_users'
    | '/_layout/_viewprofile'
    | '/_layout/dashboard'
    | '/_layout/userdashboard'
    | '/_layout/default-settings/'
    | '/_layout/_apfc/apfc/'
    | '/_layout/_devices/devices/'
    | '/_layout/_locations/locations/'
    | '/_layout/_ponds/ponds/'
    | '/_layout/_users/users/'
    | '/_layout/_viewprofile/viewprofile/'
    | '/_layout/users/add/'
    | '/_layout/_devices/devices/$device_id'
    | '/_layout/_devices/devices/$device_id/_motors'
    | '/_layout/_devices/devices/$device_id/starterbox'
    | '/_layout/_users/users/$user_id'
    | '/_layout/_users/users/$user_id/_apfc'
    | '/_layout/_users/users/$user_id/_devices'
    | '/_layout/_users/users/$user_id/_ponds'
    | '/_layout/_ponds/ponds/$pond_id/'
    | '/_layout/apfc/$apfc_id/update-settings/'
    | '/_layout/users/$user_id/update/'
    | '/_layout/_apfc/apfc/$apfc_id/activity/'
    | '/_layout/_apfc/apfc/$apfc_id/details/'
    | '/_layout/_apfc/apfc/$apfc_id/settings/'
    | '/_layout/_locations/locations/$location_id/gateways/'
    | '/_layout/_users/users/$user_id/gateways/'
    | '/_layout/_devices/devices/$device_id/_motors/motors/'
    | '/_layout/_users/users/$user_id/_apfc/apfc/'
    | '/_layout/_users/users/$user_id/_devices/devices/'
    | '/_layout/_users/users/$user_id/_ponds/ponds/'
    | '/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/'
    | '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/'
    | '/_layout/_users/users/$user_id/_devices/devices/$device_id/'
    | '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/'
    | '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/activity/'
    | '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/details/'
    | '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/settings/'
    | '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/'
    | '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/$motor_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  FetchErrorRoute: typeof FetchErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fetch-error': {
      id: '/fetch-error'
      path: '/fetch-error'
      fullPath: '/fetch-error'
      preLoaderRoute: typeof FetchErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/userdashboard': {
      id: '/_layout/userdashboard'
      path: '/userdashboard'
      fullPath: '/userdashboard'
      preLoaderRoute: typeof LayoutUserdashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_viewprofile': {
      id: '/_layout/_viewprofile'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutViewprofileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_users': {
      id: '/_layout/_users'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_ponds': {
      id: '/_layout/_ponds'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutPondsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_locations': {
      id: '/_layout/_locations'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutLocationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_devices': {
      id: '/_layout/_devices'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutDevicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_apfc': {
      id: '/_layout/_apfc'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutApfcRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/default-settings/': {
      id: '/_layout/default-settings/'
      path: '/default-settings'
      fullPath: '/default-settings'
      preLoaderRoute: typeof LayoutDefaultSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_users/users/$user_id': {
      id: '/_layout/_users/users/$user_id'
      path: '/users/$user_id'
      fullPath: '/users/$user_id'
      preLoaderRoute: typeof LayoutUsersUsersUser_idRouteImport
      parentRoute: typeof LayoutUsersRoute
    }
    '/_layout/_devices/devices/$device_id': {
      id: '/_layout/_devices/devices/$device_id'
      path: '/devices/$device_id'
      fullPath: '/devices/$device_id'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idRouteImport
      parentRoute: typeof LayoutDevicesRoute
    }
    '/_layout/users/add/': {
      id: '/_layout/users/add/'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof LayoutUsersAddIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_viewprofile/viewprofile/': {
      id: '/_layout/_viewprofile/viewprofile/'
      path: '/viewprofile'
      fullPath: '/viewprofile'
      preLoaderRoute: typeof LayoutViewprofileViewprofileIndexRouteImport
      parentRoute: typeof LayoutViewprofileRoute
    }
    '/_layout/_users/users/': {
      id: '/_layout/_users/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersUsersIndexRouteImport
      parentRoute: typeof LayoutUsersRoute
    }
    '/_layout/_ponds/ponds/': {
      id: '/_layout/_ponds/ponds/'
      path: '/ponds'
      fullPath: '/ponds'
      preLoaderRoute: typeof LayoutPondsPondsIndexRouteImport
      parentRoute: typeof LayoutPondsRoute
    }
    '/_layout/_locations/locations/': {
      id: '/_layout/_locations/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LayoutLocationsLocationsIndexRouteImport
      parentRoute: typeof LayoutLocationsRoute
    }
    '/_layout/_devices/devices/': {
      id: '/_layout/_devices/devices/'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LayoutDevicesDevicesIndexRouteImport
      parentRoute: typeof LayoutDevicesRoute
    }
    '/_layout/_apfc/apfc/': {
      id: '/_layout/_apfc/apfc/'
      path: '/apfc'
      fullPath: '/apfc'
      preLoaderRoute: typeof LayoutApfcApfcIndexRouteImport
      parentRoute: typeof LayoutApfcRoute
    }
    '/_layout/users/$user_id/update/': {
      id: '/_layout/users/$user_id/update/'
      path: '/users/$user_id/update'
      fullPath: '/users/$user_id/update'
      preLoaderRoute: typeof LayoutUsersUser_idUpdateIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apfc/$apfc_id/update-settings/': {
      id: '/_layout/apfc/$apfc_id/update-settings/'
      path: '/apfc/$apfc_id/update-settings'
      fullPath: '/apfc/$apfc_id/update-settings'
      preLoaderRoute: typeof LayoutApfcApfc_idUpdateSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_ponds/ponds/$pond_id/': {
      id: '/_layout/_ponds/ponds/$pond_id/'
      path: '/ponds/$pond_id'
      fullPath: '/ponds/$pond_id'
      preLoaderRoute: typeof LayoutPondsPondsPond_idIndexRouteImport
      parentRoute: typeof LayoutPondsRoute
    }
    '/_layout/_users/users/$user_id/_ponds': {
      id: '/_layout/_users/users/$user_id/_ponds'
      path: ''
      fullPath: '/users/$user_id'
      preLoaderRoute: typeof LayoutUsersUsersUser_idPondsRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idRoute
    }
    '/_layout/_users/users/$user_id/_devices': {
      id: '/_layout/_users/users/$user_id/_devices'
      path: ''
      fullPath: '/users/$user_id'
      preLoaderRoute: typeof LayoutUsersUsersUser_idDevicesRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idRoute
    }
    '/_layout/_users/users/$user_id/_apfc': {
      id: '/_layout/_users/users/$user_id/_apfc'
      path: '/users/$user_id'
      fullPath: '/users/$user_id'
      preLoaderRoute: typeof LayoutUsersUsersUser_idApfcRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idRoute
    }
    '/_layout/_devices/devices/$device_id/starterbox': {
      id: '/_layout/_devices/devices/$device_id/starterbox'
      path: '/starterbox'
      fullPath: '/devices/$device_id/starterbox'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idStarterboxRouteImport
      parentRoute: typeof LayoutDevicesDevicesDevice_idRoute
    }
    '/_layout/_devices/devices/$device_id/_motors': {
      id: '/_layout/_devices/devices/$device_id/_motors'
      path: '/devices/$device_id'
      fullPath: '/devices/$device_id'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idMotorsRouteImport
      parentRoute: typeof LayoutDevicesDevicesDevice_idRoute
    }
    '/_layout/_users/users/$user_id/gateways/': {
      id: '/_layout/_users/users/$user_id/gateways/'
      path: '/gateways'
      fullPath: '/users/$user_id/gateways'
      preLoaderRoute: typeof LayoutUsersUsersUser_idGatewaysIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idRoute
    }
    '/_layout/_locations/locations/$location_id/gateways/': {
      id: '/_layout/_locations/locations/$location_id/gateways/'
      path: '/locations/$location_id/gateways'
      fullPath: '/locations/$location_id/gateways'
      preLoaderRoute: typeof LayoutLocationsLocationsLocation_idGatewaysIndexRouteImport
      parentRoute: typeof LayoutLocationsRoute
    }
    '/_layout/_apfc/apfc/$apfc_id/settings/': {
      id: '/_layout/_apfc/apfc/$apfc_id/settings/'
      path: '/apfc/$apfc_id/settings'
      fullPath: '/apfc/$apfc_id/settings'
      preLoaderRoute: typeof LayoutApfcApfcApfc_idSettingsIndexRouteImport
      parentRoute: typeof LayoutApfcRoute
    }
    '/_layout/_apfc/apfc/$apfc_id/details/': {
      id: '/_layout/_apfc/apfc/$apfc_id/details/'
      path: '/apfc/$apfc_id/details'
      fullPath: '/apfc/$apfc_id/details'
      preLoaderRoute: typeof LayoutApfcApfcApfc_idDetailsIndexRouteImport
      parentRoute: typeof LayoutApfcRoute
    }
    '/_layout/_apfc/apfc/$apfc_id/activity/': {
      id: '/_layout/_apfc/apfc/$apfc_id/activity/'
      path: '/apfc/$apfc_id/activity'
      fullPath: '/apfc/$apfc_id/activity'
      preLoaderRoute: typeof LayoutApfcApfcApfc_idActivityIndexRouteImport
      parentRoute: typeof LayoutApfcRoute
    }
    '/_layout/_users/users/$user_id/_ponds/ponds/': {
      id: '/_layout/_users/users/$user_id/_ponds/ponds/'
      path: '/ponds'
      fullPath: '/users/$user_id/ponds'
      preLoaderRoute: typeof LayoutUsersUsersUser_idPondsPondsIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idPondsRoute
    }
    '/_layout/_users/users/$user_id/_devices/devices/': {
      id: '/_layout/_users/users/$user_id/_devices/devices/'
      path: '/devices'
      fullPath: '/users/$user_id/devices'
      preLoaderRoute: typeof LayoutUsersUsersUser_idDevicesDevicesIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idDevicesRoute
    }
    '/_layout/_users/users/$user_id/_apfc/apfc/': {
      id: '/_layout/_users/users/$user_id/_apfc/apfc/'
      path: '/apfc'
      fullPath: '/users/$user_id/apfc'
      preLoaderRoute: typeof LayoutUsersUsersUser_idApfcApfcIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idApfcRoute
    }
    '/_layout/_devices/devices/$device_id/_motors/motors/': {
      id: '/_layout/_devices/devices/$device_id/_motors/motors/'
      path: '/motors'
      fullPath: '/devices/$device_id/motors'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRouteImport
      parentRoute: typeof LayoutDevicesDevicesDevice_idMotorsRoute
    }
    '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/': {
      id: '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/'
      path: '/ponds/$pond_id'
      fullPath: '/users/$user_id/ponds/$pond_id'
      preLoaderRoute: typeof LayoutUsersUsersUser_idPondsPondsPond_idIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idPondsRoute
    }
    '/_layout/_users/users/$user_id/_devices/devices/$device_id/': {
      id: '/_layout/_users/users/$user_id/_devices/devices/$device_id/'
      path: '/devices/$device_id'
      fullPath: '/users/$user_id/devices/$device_id'
      preLoaderRoute: typeof LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idDevicesRoute
    }
    '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/': {
      id: '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/'
      path: '/apfc/$apfc_id'
      fullPath: '/users/$user_id/apfc/$apfc_id'
      preLoaderRoute: typeof LayoutUsersUsersUser_idApfcApfcApfc_idIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idApfcRoute
    }
    '/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/': {
      id: '/_layout/_devices/devices/$device_id/_motors/motors/$motor_id/'
      path: '/motors/$motor_id'
      fullPath: '/devices/$device_id/motors/$motor_id'
      preLoaderRoute: typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRouteImport
      parentRoute: typeof LayoutDevicesDevicesDevice_idMotorsRoute
    }
    '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/': {
      id: '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/'
      path: '/ponds/$pond_id/motors'
      fullPath: '/users/$user_id/ponds/$pond_id/motors'
      preLoaderRoute: typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idPondsRoute
    }
    '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/settings/': {
      id: '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/settings/'
      path: '/apfc/$apfc_id/settings'
      fullPath: '/users/$user_id/apfc/$apfc_id/settings'
      preLoaderRoute: typeof LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idApfcRoute
    }
    '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/details/': {
      id: '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/details/'
      path: '/apfc/$apfc_id/details'
      fullPath: '/users/$user_id/apfc/$apfc_id/details'
      preLoaderRoute: typeof LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idApfcRoute
    }
    '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/activity/': {
      id: '/_layout/_users/users/$user_id/_apfc/apfc/$apfc_id/activity/'
      path: '/apfc/$apfc_id/activity'
      fullPath: '/users/$user_id/apfc/$apfc_id/activity'
      preLoaderRoute: typeof LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idApfcRoute
    }
    '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/$motor_id/': {
      id: '/_layout/_users/users/$user_id/_ponds/ponds/$pond_id/motors/$motor_id/'
      path: '/ponds/$pond_id/motors/$motor_id'
      fullPath: '/users/$user_id/ponds/$pond_id/motors/$motor_id'
      preLoaderRoute: typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRouteImport
      parentRoute: typeof LayoutUsersUsersUser_idPondsRoute
    }
  }
}

interface LayoutApfcRouteChildren {
  LayoutApfcApfcIndexRoute: typeof LayoutApfcApfcIndexRoute
  LayoutApfcApfcApfc_idActivityIndexRoute: typeof LayoutApfcApfcApfc_idActivityIndexRoute
  LayoutApfcApfcApfc_idDetailsIndexRoute: typeof LayoutApfcApfcApfc_idDetailsIndexRoute
  LayoutApfcApfcApfc_idSettingsIndexRoute: typeof LayoutApfcApfcApfc_idSettingsIndexRoute
}

const LayoutApfcRouteChildren: LayoutApfcRouteChildren = {
  LayoutApfcApfcIndexRoute: LayoutApfcApfcIndexRoute,
  LayoutApfcApfcApfc_idActivityIndexRoute:
    LayoutApfcApfcApfc_idActivityIndexRoute,
  LayoutApfcApfcApfc_idDetailsIndexRoute:
    LayoutApfcApfcApfc_idDetailsIndexRoute,
  LayoutApfcApfcApfc_idSettingsIndexRoute:
    LayoutApfcApfcApfc_idSettingsIndexRoute,
}

const LayoutApfcRouteWithChildren = LayoutApfcRoute._addFileChildren(
  LayoutApfcRouteChildren,
)

interface LayoutDevicesDevicesDevice_idMotorsRouteChildren {
  LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute: typeof LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute
  LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute: typeof LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute
}

const LayoutDevicesDevicesDevice_idMotorsRouteChildren: LayoutDevicesDevicesDevice_idMotorsRouteChildren =
  {
    LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute:
      LayoutDevicesDevicesDevice_idMotorsMotorsIndexRoute,
    LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute:
      LayoutDevicesDevicesDevice_idMotorsMotorsMotor_idIndexRoute,
  }

const LayoutDevicesDevicesDevice_idMotorsRouteWithChildren =
  LayoutDevicesDevicesDevice_idMotorsRoute._addFileChildren(
    LayoutDevicesDevicesDevice_idMotorsRouteChildren,
  )

interface LayoutDevicesDevicesDevice_idRouteChildren {
  LayoutDevicesDevicesDevice_idMotorsRoute: typeof LayoutDevicesDevicesDevice_idMotorsRouteWithChildren
  LayoutDevicesDevicesDevice_idStarterboxRoute: typeof LayoutDevicesDevicesDevice_idStarterboxRoute
}

const LayoutDevicesDevicesDevice_idRouteChildren: LayoutDevicesDevicesDevice_idRouteChildren =
  {
    LayoutDevicesDevicesDevice_idMotorsRoute:
      LayoutDevicesDevicesDevice_idMotorsRouteWithChildren,
    LayoutDevicesDevicesDevice_idStarterboxRoute:
      LayoutDevicesDevicesDevice_idStarterboxRoute,
  }

const LayoutDevicesDevicesDevice_idRouteWithChildren =
  LayoutDevicesDevicesDevice_idRoute._addFileChildren(
    LayoutDevicesDevicesDevice_idRouteChildren,
  )

interface LayoutDevicesRouteChildren {
  LayoutDevicesDevicesIndexRoute: typeof LayoutDevicesDevicesIndexRoute
  LayoutDevicesDevicesDevice_idRoute: typeof LayoutDevicesDevicesDevice_idRouteWithChildren
}

const LayoutDevicesRouteChildren: LayoutDevicesRouteChildren = {
  LayoutDevicesDevicesIndexRoute: LayoutDevicesDevicesIndexRoute,
  LayoutDevicesDevicesDevice_idRoute:
    LayoutDevicesDevicesDevice_idRouteWithChildren,
}

const LayoutDevicesRouteWithChildren = LayoutDevicesRoute._addFileChildren(
  LayoutDevicesRouteChildren,
)

interface LayoutLocationsRouteChildren {
  LayoutLocationsLocationsIndexRoute: typeof LayoutLocationsLocationsIndexRoute
  LayoutLocationsLocationsLocation_idGatewaysIndexRoute: typeof LayoutLocationsLocationsLocation_idGatewaysIndexRoute
}

const LayoutLocationsRouteChildren: LayoutLocationsRouteChildren = {
  LayoutLocationsLocationsIndexRoute: LayoutLocationsLocationsIndexRoute,
  LayoutLocationsLocationsLocation_idGatewaysIndexRoute:
    LayoutLocationsLocationsLocation_idGatewaysIndexRoute,
}

const LayoutLocationsRouteWithChildren = LayoutLocationsRoute._addFileChildren(
  LayoutLocationsRouteChildren,
)

interface LayoutPondsRouteChildren {
  LayoutPondsPondsIndexRoute: typeof LayoutPondsPondsIndexRoute
  LayoutPondsPondsPond_idIndexRoute: typeof LayoutPondsPondsPond_idIndexRoute
}

const LayoutPondsRouteChildren: LayoutPondsRouteChildren = {
  LayoutPondsPondsIndexRoute: LayoutPondsPondsIndexRoute,
  LayoutPondsPondsPond_idIndexRoute: LayoutPondsPondsPond_idIndexRoute,
}

const LayoutPondsRouteWithChildren = LayoutPondsRoute._addFileChildren(
  LayoutPondsRouteChildren,
)

interface LayoutUsersUsersUser_idApfcRouteChildren {
  LayoutUsersUsersUser_idApfcApfcIndexRoute: typeof LayoutUsersUsersUser_idApfcApfcIndexRoute
  LayoutUsersUsersUser_idApfcApfcApfc_idIndexRoute: typeof LayoutUsersUsersUser_idApfcApfcApfc_idIndexRoute
  LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRoute: typeof LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRoute
  LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRoute: typeof LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRoute
  LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRoute: typeof LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRoute
}

const LayoutUsersUsersUser_idApfcRouteChildren: LayoutUsersUsersUser_idApfcRouteChildren =
  {
    LayoutUsersUsersUser_idApfcApfcIndexRoute:
      LayoutUsersUsersUser_idApfcApfcIndexRoute,
    LayoutUsersUsersUser_idApfcApfcApfc_idIndexRoute:
      LayoutUsersUsersUser_idApfcApfcApfc_idIndexRoute,
    LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRoute:
      LayoutUsersUsersUser_idApfcApfcApfc_idActivityIndexRoute,
    LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRoute:
      LayoutUsersUsersUser_idApfcApfcApfc_idDetailsIndexRoute,
    LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRoute:
      LayoutUsersUsersUser_idApfcApfcApfc_idSettingsIndexRoute,
  }

const LayoutUsersUsersUser_idApfcRouteWithChildren =
  LayoutUsersUsersUser_idApfcRoute._addFileChildren(
    LayoutUsersUsersUser_idApfcRouteChildren,
  )

interface LayoutUsersUsersUser_idDevicesRouteChildren {
  LayoutUsersUsersUser_idDevicesDevicesIndexRoute: typeof LayoutUsersUsersUser_idDevicesDevicesIndexRoute
  LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRoute: typeof LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRoute
}

const LayoutUsersUsersUser_idDevicesRouteChildren: LayoutUsersUsersUser_idDevicesRouteChildren =
  {
    LayoutUsersUsersUser_idDevicesDevicesIndexRoute:
      LayoutUsersUsersUser_idDevicesDevicesIndexRoute,
    LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRoute:
      LayoutUsersUsersUser_idDevicesDevicesDevice_idIndexRoute,
  }

const LayoutUsersUsersUser_idDevicesRouteWithChildren =
  LayoutUsersUsersUser_idDevicesRoute._addFileChildren(
    LayoutUsersUsersUser_idDevicesRouteChildren,
  )

interface LayoutUsersUsersUser_idPondsRouteChildren {
  LayoutUsersUsersUser_idPondsPondsIndexRoute: typeof LayoutUsersUsersUser_idPondsPondsIndexRoute
  LayoutUsersUsersUser_idPondsPondsPond_idIndexRoute: typeof LayoutUsersUsersUser_idPondsPondsPond_idIndexRoute
  LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRoute: typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRoute
  LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRoute: typeof LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRoute
}

const LayoutUsersUsersUser_idPondsRouteChildren: LayoutUsersUsersUser_idPondsRouteChildren =
  {
    LayoutUsersUsersUser_idPondsPondsIndexRoute:
      LayoutUsersUsersUser_idPondsPondsIndexRoute,
    LayoutUsersUsersUser_idPondsPondsPond_idIndexRoute:
      LayoutUsersUsersUser_idPondsPondsPond_idIndexRoute,
    LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRoute:
      LayoutUsersUsersUser_idPondsPondsPond_idMotorsIndexRoute,
    LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRoute:
      LayoutUsersUsersUser_idPondsPondsPond_idMotorsMotor_idIndexRoute,
  }

const LayoutUsersUsersUser_idPondsRouteWithChildren =
  LayoutUsersUsersUser_idPondsRoute._addFileChildren(
    LayoutUsersUsersUser_idPondsRouteChildren,
  )

interface LayoutUsersUsersUser_idRouteChildren {
  LayoutUsersUsersUser_idApfcRoute: typeof LayoutUsersUsersUser_idApfcRouteWithChildren
  LayoutUsersUsersUser_idDevicesRoute: typeof LayoutUsersUsersUser_idDevicesRouteWithChildren
  LayoutUsersUsersUser_idPondsRoute: typeof LayoutUsersUsersUser_idPondsRouteWithChildren
  LayoutUsersUsersUser_idGatewaysIndexRoute: typeof LayoutUsersUsersUser_idGatewaysIndexRoute
}

const LayoutUsersUsersUser_idRouteChildren: LayoutUsersUsersUser_idRouteChildren =
  {
    LayoutUsersUsersUser_idApfcRoute:
      LayoutUsersUsersUser_idApfcRouteWithChildren,
    LayoutUsersUsersUser_idDevicesRoute:
      LayoutUsersUsersUser_idDevicesRouteWithChildren,
    LayoutUsersUsersUser_idPondsRoute:
      LayoutUsersUsersUser_idPondsRouteWithChildren,
    LayoutUsersUsersUser_idGatewaysIndexRoute:
      LayoutUsersUsersUser_idGatewaysIndexRoute,
  }

const LayoutUsersUsersUser_idRouteWithChildren =
  LayoutUsersUsersUser_idRoute._addFileChildren(
    LayoutUsersUsersUser_idRouteChildren,
  )

interface LayoutUsersRouteChildren {
  LayoutUsersUsersIndexRoute: typeof LayoutUsersUsersIndexRoute
  LayoutUsersUsersUser_idRoute: typeof LayoutUsersUsersUser_idRouteWithChildren
}

const LayoutUsersRouteChildren: LayoutUsersRouteChildren = {
  LayoutUsersUsersIndexRoute: LayoutUsersUsersIndexRoute,
  LayoutUsersUsersUser_idRoute: LayoutUsersUsersUser_idRouteWithChildren,
}

const LayoutUsersRouteWithChildren = LayoutUsersRoute._addFileChildren(
  LayoutUsersRouteChildren,
)

interface LayoutViewprofileRouteChildren {
  LayoutViewprofileViewprofileIndexRoute: typeof LayoutViewprofileViewprofileIndexRoute
}

const LayoutViewprofileRouteChildren: LayoutViewprofileRouteChildren = {
  LayoutViewprofileViewprofileIndexRoute:
    LayoutViewprofileViewprofileIndexRoute,
}

const LayoutViewprofileRouteWithChildren =
  LayoutViewprofileRoute._addFileChildren(LayoutViewprofileRouteChildren)

interface LayoutRouteChildren {
  LayoutApfcRoute: typeof LayoutApfcRouteWithChildren
  LayoutDevicesRoute: typeof LayoutDevicesRouteWithChildren
  LayoutLocationsRoute: typeof LayoutLocationsRouteWithChildren
  LayoutPondsRoute: typeof LayoutPondsRouteWithChildren
  LayoutUsersRoute: typeof LayoutUsersRouteWithChildren
  LayoutViewprofileRoute: typeof LayoutViewprofileRouteWithChildren
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutUserdashboardRoute: typeof LayoutUserdashboardRoute
  LayoutDefaultSettingsIndexRoute: typeof LayoutDefaultSettingsIndexRoute
  LayoutUsersAddIndexRoute: typeof LayoutUsersAddIndexRoute
  LayoutApfcApfc_idUpdateSettingsIndexRoute: typeof LayoutApfcApfc_idUpdateSettingsIndexRoute
  LayoutUsersUser_idUpdateIndexRoute: typeof LayoutUsersUser_idUpdateIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutApfcRoute: LayoutApfcRouteWithChildren,
  LayoutDevicesRoute: LayoutDevicesRouteWithChildren,
  LayoutLocationsRoute: LayoutLocationsRouteWithChildren,
  LayoutPondsRoute: LayoutPondsRouteWithChildren,
  LayoutUsersRoute: LayoutUsersRouteWithChildren,
  LayoutViewprofileRoute: LayoutViewprofileRouteWithChildren,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutUserdashboardRoute: LayoutUserdashboardRoute,
  LayoutDefaultSettingsIndexRoute: LayoutDefaultSettingsIndexRoute,
  LayoutUsersAddIndexRoute: LayoutUsersAddIndexRoute,
  LayoutApfcApfc_idUpdateSettingsIndexRoute:
    LayoutApfcApfc_idUpdateSettingsIndexRoute,
  LayoutUsersUser_idUpdateIndexRoute: LayoutUsersUser_idUpdateIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LayoutRoute: LayoutRouteWithChildren,
  FetchErrorRoute: FetchErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
